namespace PostgresMonitor.Core.DTOs;

public readonly record struct IndexDetailsDto(
    string SchemaName,
    string TableName,
    string IndexName,
    long IndexScans,
    long IndexTuplesRead,
    long IndexTuplesFetched,
    long IndexSize,
    long TableSize,
    double IndexPercentOfTable,
    bool IsUnique,
    bool IsPrimary,
    bool IsValid,
    string IndexDefinition,
    long TableSeqScans,
    long TableIndexScans,
    double TableIndexUsageRatio,
    long TableLiveTuples,
    long TableDeadTuples,
    double TableDeadTupleRatio,
    long TableInserts,
    long TableUpdates,
    long TableDeletes,
    DateTime? LastVacuum,
    DateTime? LastAutovacuum,
    DateTime? LastAnalyze,
    DateTime? LastAutoanalyze,
    long VacuumCount,
    long AutovacuumCount,
    long AnalyzeCount,
    long AutoanalyzeCount,
    long TotalReorganizations
);
